FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY ./dotnet8 ./
RUN dotnet publish --configuration Release --output ./out --runtime linux-x64 --self-contained

FROM mcr.microsoft.com/dotnet/runtime-deps:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

ENTRYPOINT ["./dotnet8"]
